---
- name: Create Credentials Username and SSH Key
  hosts: workstation

  tasks:
    - name: "Read in SSH Key"
      ansible.builtin.slurp:
        src: /home/student/.ssh/lab_rsa
      register: SSH_KEY

    - name: "DO467 Machine Credentials - CH3 Demo - Key"
      ansible.controller.credential:
        name: "DO467 Machine Credentials - CH3 Demo - Key"
        description: "SSH Username and SSH Key"
        organization: Red Hat Training
        credential_type: Machine
        inputs:
          username: devops
          ssh_key_data: "{{ SSH_KEY['content'] | b64decode }}"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present

## Playbook works with the Ansible Controller Collection installed
## [student@workstation CH3]$ ansible-galaxy collection install collections/ansible-controller-4.2.0.tar.gz -p collections/
## [student@workstation CH3]$ ansible-playbook Create_Machine_Creds_SSH_Key.yml

## Fails on lookup with EEI
## [WARNING]: Unable to find '/home/student/.ssh/lab_rsa' in expected paths (use -vvvvv to see paths)

### Solution - EE doesn't have access and can't mount /home directly into the container (EE)
### The SLURP module can be used to read in files, but the contents are B64 encoded
### Need to decode the content from the "SLURP" module
