---
- name: Create Credentials Username and Password
  hosts: localhost

  tasks:
    - ansible.controller.credential:
        name: "DO467 Machine Credentials - CH3 Demo - Password"
        description: "SSH Username and Password"
        organization: Red Hat Training
        credential_type: Machine
        inputs:
          username: devops
          password: redhat
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present
