---
- name: Playbook to Configure Controller Inventory
  hosts: localhost
  tasks:

    - name: Create DO467 Inventory - CH3 Demo
      ansible.controller.inventory:
        name: "DO467 CH3 - Demo Inventory"
        organization: "Red Hat Training"
        state: "present"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
