---
- name: Create Job WorkflowTemplate CH6
  hosts: localhost

  tasks:

### Create Job Workflow Template

    - name: Create Job Workflow Template CH6
      ansible.controller.workflow_job_template:
        name: "DO467 CH6 Deploy Workflow Job Template"
        organization: Red Hat Training
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present

### Run Job Template for QA Environment
    - name: Create Run Job Template QA Environment Step
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Execute QA
        workflow_job_template: "DO467 CH6 Deploy Workflow Job Template"
        unified_job_template: "DO467 Deploy Web Demo Job Template"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        extra_data:
          inv_host_var: QA


### Run Job Template for Dev Environment
    - name: Create Run Job Template Dev Environment Step
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Execute DEV
        workflow_job_template: "DO467 CH6 Deploy Workflow Job Template"
        unified_job_template: "DO467 Deploy Web Demo Job Template"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        extra_data:
          inv_host_var: DEV
        success_nodes:
          - Execute QA

### Synchronize Inventory
    - name: Create Synchronize Inventory Source Step
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Synchronize Inventory
        workflow_job_template: "DO467 CH6 Deploy Workflow Job Template"
        unified_job_template: "DO467 Demo Project Inventory Source"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        success_nodes:
          - Execute DEV

### Synchronize Project
    - name: Create Synchronize Project Step
      ansible.controller.workflow_job_template_node:
        organization: Red Hat Training
        identifier: Synchronize Project
        workflow_job_template: "DO467 CH6 Deploy Workflow Job Template"
        unified_job_template: "DO467 Demo Project"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        success_nodes:
          - Synchronize Inventory



